import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {useState } from "react";


export default function Home() {
  const [image, setImage] = useState(null);
  const [createObjectURL, setCreateObjectURL] = useState(null);
  const [outputImg, setOutputImage] = useState(null);

  // const [state, setState] = useState({selectedFile: null})

  const convertBase64 = (file) => {
    return new Promise((resolve, reject) => {
      const fileReader = new FileReader();
      fileReader.readAsDataURL(file);

      fileReader.onload = () => {
        resolve(fileReader?.result);
      };

      fileReader.onerror = (error) => {
        reject(error);
      };
    });
  };

  const uploadToClient = async (event) => {
    if (event.target.files && event.target.files[0]) {
      const i = event.target.files[0];
      const base64 = await convertBase64(i);

      setImage(base64);
      setCreateObjectURL(URL.createObjectURL(i));
      // setState({ selectedFile: event.target.files[0] })
    
    
    }
  };


  const submitContact = async (event) => {
    event.preventDefault();
    // console.log(image)

    const response = await fetch("/api/object-detection", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        img: image,
      }),
    });

    const responseData = await response.json();

    setOutputImage(responseData.data.output_img)

    // obj_cords: [ { name: 'bottle_1', x1: 115, y1: 45, x2: 384, y2: 676 } ]

    const obj_cords = responseData.data.obj_cords

  };



  return (
    <div className={styles.container}>
      <Head>
        <title>Object Detection API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Object Detection API
        </h1>

        <p className={styles.description}>
          get started with your image
        </p>

  
        <form method='POST' onSubmit={submitContact} className={styles.grid}>
          <div className={styles.card}>
            <h2>Input Image</h2>
            <div className={styles.img_container}>
              <img src={createObjectURL} className={styles.img} />
            </div>
            <div className={styles.upload}>
              <input type="file" name="inp_img" id='inp_img' onChange={uploadToClient} />
              
              <button type='submit' >submit</button>
            
            </div>
            
          </div>

          <div className={styles.card}>
            <h2>Output Image</h2>
            <div className={styles.img_container}>
              <img src={`data:image/png;base64,${outputImg}`} className={styles.img} />
              
            </div>
            
            
          </div>
        </form>
          
      </main>
    </div>
  )
}
